[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/attendance"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSdDDkEwgssE2WL3AcZEMVNCEGLZXN6yEHXZ1GBI_VgrDeMoKg/viewform"
  status = 301
  force = true

[[redirects]]
  from = "/attendance/"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSdDDkEwgssE2WL3AcZEMVNCEGLZXN6yEHXZ1GBI_VgrDeMoKg/viewform"
  status = 301
  force = true

[[redirects]]
  from = "/seaso26"
  to = "https://forms.gle/hJtHBtT5BRexuVgj8"
  status = 301
  force = true

[[redirects]]
  from = "/seaso26/"
  to = "https://forms.gle/hJtHBtT5BRexuVgj8"
  status = 301
  force = true

[[redirects]]
  from = "/seaso26-volunteer"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSeWoyN973oVwosgE5Sq15u9V8bCUttuo9gyXe6brqs_AQxRrQ/viewform"
  status = 301
  force = true

[[redirects]]
  from = "/seaso26-volunteer/"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSeWoyN973oVwosgE5Sq15u9V8bCUttuo9gyXe6brqs_AQxRrQ/viewform"
  status = 301
  force = true

[[redirects]]
  from = "/store"
  to = "https://sasc.bigcartel.com"
  status = 301
  force = true

[[redirects]]
  from = "/seagrad26"
to = "/events"
status = 302
force = true

[[redirects]]
from = "/seagrad2026"
to = "/events"
status = 302
force = true

[[redirects]]
from = "/tos-vendor"
to = "/events"
status = 302
force = true

[[redirects]]
from = "/tos-performer"
to = "/events"
status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 